gluciani73/StudyRooms

- api/seeder.js
- api/src/app.js
- api/src/controllers/usersController.js
cambie avatar en usuarios para q devuelva la url de una imagen, y agregue error handler en el index.js
> ahora los usuarios de test devuelven un url valido para la photo de perfil y se agrega error handler

- client/src/componentes/Usuarios/UserForm.jsx
> The sweetalert dependency was updated.

- api/src/controllers/answersController.js
- api/src/models/Answer.js
- api/src/routes/answer.js
- client/src/Controllers/Actions/answerActions.js
- client/src/componentes/answers/AnswerList.js
> The answer backEnd and frontEnd components were updated.

- api/src/controllers/answersController.js
- api/src/controllers/questionsController.js
- api/src/routes/answer.js
- api/src/routes/question.js
Se agrega la ruta del backend para GET de una pregunta con su questionID (contiene las respuestas y datos del usuario) y otro GET que trae todas las preguntas, con sus respuestas y usuarios.
> GET de pregunta con questionId y todas las preguntas

- client/src/Controllers/Actions/loginActions.js
- client/src/Controllers/Reducer/loginReducer.js
- client/src/componentes/Home/Home.jsx
- client/src/componentes/LandingPage/LandingPage.jsx
- client/src/componentes/NavBar/NavBar.jsx
- client/src/componentes/Usuarios/Login.jsx
- client/src/componentes/Usuarios/UserForm.jsx
Buenas dejo aca el state global ( userInfo ) con los datos del usuario, tambien tuve que hacer un fix que no renderizaba por el localstorage el home. Cualquier cosa avisan
> Login small Fix + State Users

- api/src/controllers/usersController.js
- api/src/routes/users.js
ahi agrego el account recovery por mail
> recuperacion de cuenta hecha

- client/src/Controllers/Actions/answerActions.js
- client/src/componentes/Usuarios/userUtilities.js
- client/src/componentes/answers/AnswerList.js
Only frontEnd updates. note, they are not going to work until the back is updated and connected.
> Front Answer components update

- api/seeder.js
- api/src/controllers/commentsController.js
- api/src/db.js
- api/src/models/Comment.js
- api/src/routes/comment.js
- api/src/routes/index.js
- api/testData.json
> The backend was updated with the comments endpoints.

- client/src/Controllers/Actions/answerActions.js
- client/src/componentes/Usuarios/userUtilities.js
- client/src/componentes/answers/AnswerCreate.js
- client/src/componentes/answers/AnswerList.js
1. if the user does not have an answer, the create form is displayed:
2. after the user creates his answer, the create form is hidden:
3. when the user clicks the edit button on his comment, the edit form is displayed:
4. after updating the answer and clicking the save button, the answer is updated:
> The Answer's create, edit and delete buttons were connected

- client/src/Controllers/Actions/answerActions.js
- client/src/Controllers/Actions/commentActions.js
- client/src/componentes/answers/AnswerList.js
- client/src/componentes/comments/CommentList.js
- client/src/constants.js
1. if the user is not logged, the edit, delete and create buttons are hidden:
2. the user can add several comments and edit and delete only those commits that he/she has created:
> The ComponentList was updated to connect with the backend. 

- api/src/controllers/answersController.js
- api/src/controllers/questionsController.js
Actualice los controller para editar preguntas y respuestas
> Update Answer y Update Questions

- client/src/Controllers/Actions/answerActions.js
- client/src/Controllers/Actions/commentActions.js
- client/src/componentes/Preguntas/QuestionDetail.jsx
> Integration with QuestionDetail and AnswerList and CommentList

- client/src/componentes/Preguntas/QuestionDetail.jsx
> navbar en questiondetails

- api/src/routes/googleAuth.js
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/Controllers/Actions/loginActions.js
- client/src/Controllers/Reducer/loginReducer.js
- client/src/componentes/Home/Home.jsx
- client/src/componentes/Home/TOS.jsx
- client/src/componentes/NavBar/NavBar.jsx
- client/src/componentes/Usuarios/GoogleAuth.jsx
- client/src/componentes/Usuarios/Login.jsx
- client/src/componentes/Usuarios/Profile.jsx
- client/src/componentes/Usuarios/UserForm.jsx
agrego algunos "alt" a imagenes (no cambia nada pero ya no tira error)
saco alguna q otra linea q no se usaba (tampoco deberia joder, pero miren por si acaso ;) )
agretodo lo del google auth del front
> google auth desde el front

- api/seeder.js
- api/src/controllers/answersController.js
- api/src/models/Answer.js
- api/testData.json
- client/package-lock.json
- client/package.json
- client/src/componentes/answers/AnswerList.js
With these backend updates, the front will display the rating and votes information:
> The backend rating and votes information was added to the Answer code.

- client/package-lock.json
- client/package.json
- client/src/componentes/answers/AnswerList.js
Note the back needs to be updated to display the required info.
> The rating and upVotes information was added to the AnswerList component

- client/src/componentes/answers/AnswerList.css
- client/src/componentes/answers/AnswerList.js
- client/src/componentes/comments/CommentCreate.css
- client/src/componentes/comments/CommentCreate.js
- client/src/componentes/comments/CommentList.css
- client/src/componentes/comments/CommentList.js
The rating stars and thumb-up image were re-arranged:
The comment list and comment create were moved right:
> Answer and Comment css styles were updated

- client/src/Controllers/Actions/answerActions.js
- client/src/Controllers/Reducer/answerReducer.js
- client/src/componentes/answers/AnswerList.css
- client/src/componentes/answers/AnswerList.js
The thumb-up image can be clicked to increase the other person's answers.
1. here it is with 21 votes:
2. here it is with 28 votes: 
Note in this version, the user can vote as many times as he/she wants.
> The Answer's vote increment was implemented.

- client/src/componentes/answers/AnswerList.js
One alert was added to the vote link:
And the other to the delete button:
> Two alerts were added to AnswerLis

- client/src/Controllers/Actions/answerActions.js
- client/src/Controllers/Reducer/answerReducer.js
- client/src/componentes/answers/AnswerList.css
- client/src/componentes/answers/AnswerList.js
Also, the 'order by' widget was added:
> The Answer's vote increment was updated.

- api/src/controllers/usersController.js
ahora solo cambia lo que se le manda y no acepta strings vacios
> fixed back del updateUser

- README.md
Agrego rutas de deploy al readme
> Rutas al deploy en  README.md

- api/index.js
Cambio forse a false para no perder los datos que ya tenemos en la DB. si en algun momento lo necesitamos lo volvemos a true.
> cambio  a force: false

- api/seeder.js
- api/src/controllers/usersController.js
agregué un test user nuevo q es admin, y el username y password son : admin
y ahora al cambiar elprofile data, devuelve nuevo token con la nueva info para actualizar en el front
> Fix update user

- api/index.js
- api/src/controllers/categoryController.js
- api/src/routes/categories.js
Se agrega create, update, y delete, read ya estaba ...
pasamos el server a force: true hasta modificar el seeder porque sino da error y no levanta..
> CRUD de  categories

- client/src/Controllers/Actions/answerActions.js
- client/src/Controllers/Reducer/answerReducer.js
- client/src/componentes/answers/AnswerList.js
1. The answer rating is displayed empty when the user has not assigned a rate to that particular answer. The user can rate other users' answers:
2. Once the user rates the answer, the rate average and the number of rates are updated
> The AnswerList was updated to show/assing the answer's rating

- client/src/componentes/answers/AnswerList.css
- client/src/componentes/answers/AnswerList.js
1. The user rate assignation was updated
2. The answer rate average and votes were updated
> The answers rating and votes css elements were updated.

- api/index.js
- api/src/controllers/questionsController.js
- api/src/models/Question.js
Aggiungo isDeleted all'modelo di database , e faccio le modifche che servono al controller per fare l'eliminazione logica invece del destroy.
> Deleted Question ahora borrado logico

- client/src/App.js
- client/src/Controllers/Actions/userAction.js
- client/src/Controllers/Reducer/userReducer.js
- client/src/componentes/NavBar/NavBar.jsx
- client/src/componentes/adminPanel/UserList.css
- client/src/componentes/adminPanel/UserList.jsx
- client/src/constants.js
Also, the user button was added to the navbar. Please note the button is only displayed if the user is an admin. 
Also, the adminPanel can only be accessed by an admin user: 
Also, the admin panel URL can be accessed but if the user is not an admin user, it does not display any user data:
> The adminPanel's userList view was added

- api/src/controllers/usersController.js
...to save all the user's fields and returns all of them except the password.
> [back] The userController's updateUser was updated

- api/src/controllers/questionsController.js
- api/src/routes/question.js
Consulta para ver las preguntas que fueron eliminadas, y consulta para ver todas las preguntas (marcadas como isDeleted true or false)
> agrego consulta Deleted Questions, y All Questions

- client/src/Controllers/Actions/userAction.js
- client/src/Controllers/Reducer/userReducer.js
The userAction's was updated to send the received userData from the back to the reducer. Also, the userReducer's UPDATE_USERS case was added to update the userList in the store.
> [front] The userAction's and userReducer were updated.

- client/src/componentes/adminPanel/UserEdit.jsx
- client/src/componentes/adminPanel/UserForm.css
- client/src/componentes/adminPanel/UserForm.jsx
- client/src/componentes/adminPanel/UserList.jsx
> [front] The adminPanel's userList's edit functionality was implemented.

- api/seeder.js
el admin estaba como usuario desactivado, no se como probarían en el front lo del admin ! ahi anda bien
> hago q el admin este activo, (antes estaba en false)

- client/src/componentes/adminPanel/UserForm.css
- client/src/componentes/adminPanel/UserForm.jsx
> [front] The adminPanel's userList's edit's avatar field was added.

- client/src/Controllers/Reducer/userReducer.js
to handle the adminPanel's userCreate's calls.
> [front] The userReducer was updated with the CREATE_USER option 

- client/src/Controllers/Actions/userAction.js
- client/src/componentes/adminPanel/UserCreate.css
- client/src/componentes/adminPanel/UserCreate.jsx
- client/src/componentes/adminPanel/UserForm.jsx
- client/src/componentes/adminPanel/UserList.jsx
- client/src/componentes/answers/AnswerForm.css
- client/src/componentes/comments/CommentForm.css
1. The adminPanel createUser form:
2. The adminPanel de-activate and activate buttons:
> The adminPanel create user form and de-activate and activate buttons were added.

- client/scss/style.scss
- client/src/Controllers/Actions/questionsActions.js
- client/src/componentes/Preguntas/AskQuestion.jsx
- client/src/componentes/likebutton/LogDel.jsx
se adapta el boton de delete question para que use la ruta de guillermo
al presionar el botón de delete te manda de regreso a home
> question log delete completo

- client/src/App.js
- client/src/componentes/NavBar/NavBar.jsx
> [front] The Users and Categories buttons were added to the navBar.

- client/src/Controllers/Actions/categoryActions.js
- client/src/Controllers/Reducer/categoryReducer.js
- client/src/Controllers/Reducer/index.js
- client/src/componentes/categorias/CategoryCreate.jsx
- client/src/componentes/categorias/CategoryEdit.jsx
- client/src/componentes/categorias/CategoryForm.jsx
- client/src/componentes/categorias/CategoryList.jsx
1. The Admin Category list and the Delete button:
2. The Admin Edit Category:
3. The Admin Create Category:
> The Admin CRUD for categories was added.

- client/src/componentes/Footer/Footer.jsx
- client/src/componentes/Home/Home.jsx
- client/src/componentes/Preguntas/AskQuestion.jsx
- client/src/componentes/Preguntas/Question.jsx
- client/src/componentes/Preguntas/QuestionDetail.jsx
- client/src/componentes/likebutton/LogDel.jsx
se hace display de las categorias de las preguntas para hacer validaciones de filtros
> cambio en questions

- api/src/models/User.js
Actualizo a decimal el campo que acumula los importes donados.
> Update to DECIMAL the amountDonated

- client/src/componentes/answers/AnswerList.js
A warning was removed from the console.
> [front] The AnswerList's useEffects were updated with questionId

- client/src/Controllers/Reducer/QuestionReducer.js
- client/src/componentes/NavBar/SearchBar.jsx
- client/src/componentes/SearchBar/SearchBar.jsx
Se arregla segundo filtro, traia todas las categorias en lugar de las que  cumplian la primera condicion
> Se soluciona tema de segundo filtro

- api/testData.json
- client/src/componentes/LandingPage/LandingPage.jsx
- client/src/componentes/LandingPage/navLanding.module.css
- client/src/componentes/NavBar/NavBar-nologin.jsx
- client/src/componentes/Usuarios/UserForm.jsx
- client/src/componentes/answers/AnswerCreate.css
- client/src/componentes/answers/AnswerList.css
- client/src/componentes/comments/CommentCreate.css
- client/src/componentes/comments/CommentList.css
> The CommentList and AnswerList css files were updated to align them with QuestionDetail.

- client/src/componentes/answers/AnswerCreate.css
- client/src/componentes/answers/AnswerCreate.js
- client/src/componentes/answers/AnswerList.css
- client/src/componentes/answers/AnswerList.js
- client/src/componentes/comments/CommentCreate.css
- client/src/componentes/comments/CommentCreate.js
- client/src/componentes/comments/CommentList.css
- client/src/componentes/comments/CommentList.js
> [front] The CommentList and AnswerList css files were updated - 2

- client/src/componentes/Home/Filters.jsx
si el primero esta en all el segundo no renderiza
el segundo se resetea al dejar de renderizar
> fixes a filtros

- client/src/componentes/Home/Home.jsx
no mas se cambia el texto de 
"esto no existe"
a 
"your search criteria did not match any filters"
porque se ve mas cool
> cambio texto de busqueda sin resultados
